### ISSUE TITLE
Call functions decorated with @cmd from Python and how to use parse_args() to get default values

### ISSUE THREAD

**Issue by lumbric** [wbolster/aaargh#8]
This is more a question than a bug or a very thought-out feature request. Using your library I'd like to be able to call functions using command line sub commands or calling them directly as functions from other parts of the code or using a python shell. Of course I do not want to specify all arguments and their default values twice (once as `@app.cmd_arg` decorator and once in the function definition). So I use kwargs instead for the function signature:

```
@app.cmd_arg('-c', default='my_default', help='some config flag')
def my_cmd(**kwargs):
     print kwargs['c']
```

Using command line and providing command line parameters everything works fine. But if I want to call `my_cmd()` on the python shell, what would be the best way to get the default value of `kwargs['c']`? 

I subclassed aaargh.App and extended the decorator @cmd and tried to pass all keyword arguments to `my_cmd`. If they are not given as function parameters I'd like to retrieve them from Argparse. The problem is, Argparse does not provide any easy way to get a dictionary of keyword arguments filled with the default values. Argparse provides the method [parse_args()](http://docs.python.org/2/library/argparse.html#argparse.ArgumentParser.parse_args). But it exits with a `SystemExit` exception and prints unwanted help text if there is something wrong with the arguments. Something wrong includes also required arguments. If I call a function decorated with `@app.cmd` directly from python, `parse_args()` would never see the arguments I pass to the function and always complain that the required arguments are missing.

Should this issue go upstream to Argparse? Do have any simple suggestions how to deal with this problem?

**Comment by wbolster** [comment]
closing; i have abandoned this project
